{{- if .Values.tls.createClusterIssuer | default false }}
# Cert-Manager ClusterIssuer for Let's Encrypt
# DISABLED: ClusterIssuer already exists (cluster-wide resource)
# Helm will use the existing cluster issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.clusterIssuer }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: kong
{{- end }}
