{{- if .Values.promtail.enabled }}
# Promtail ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: {{ .Values.global.namespace }}

---
# Promtail ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-{{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "watch", "list"]

---
# Promtail ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-{{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: promtail-{{ .Values.global.namespace }}
  apiGroup: rbac.authorization.k8s.io

---
# Promtail ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Values.global.namespace }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - cri: {}
        relabel_configs:
          # Drop namespace filter to see if we find anything
          # - source_labels: [__meta_kubernetes_namespace]
          #   action: keep
          #   regex: {{ .Values.global.namespace }}
          
          # IMPORTANT: Only scrape pods on the same node
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: __host__
          
          # Add namespace label
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          
          # Add pod name label
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          
          # Add container name label
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          
          # Add app label
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          
          # Add node name
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          
          # Set path - GKE uses: /var/log/pods/namespace_podname_uid/container/*.log
          # We use a wildcard to match the full directory name which includes namespace_podname_uid
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            separator: /
            target_label: __path__
            regex: ([^/]+)/([^/]+)/([^/]+)/([^/]+)
            replacement: /var/log/pods/$1_$2_$3/$4/*.log

---
# Promtail DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: {{ .Values.global.namespace }}
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: {{ .Values.promtail.image }}:{{ .Values.promtail.tag }}
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
          ports:
            - containerPort: 3101
              name: http-metrics
          resources:
            {{- toYaml .Values.promtail.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
{{- end }}
