# Auth Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: swappo
spec:
  replicas: 1  # Run 2 instances for high availability
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: default
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      # Main application container
      - name: auth-service
        image: ghcr.io/swapppo/swappo-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        # Database connection via Cloud SQL Proxy
        - name: DATABASE_URL
          value: postgresql://auth_user:Admin@127.0.0.1:5432/swappo_auth
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: secret-key
        - name: REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: refresh-secret-key
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: REFRESH_TOKEN_EXPIRE_DAYS
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: REFRESH_TOKEN_EXPIRE_DAYS
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: ENVIRONMENT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "$(DB_INSTANCE_CONNECTION_NAME)"
        env:
        - name: DB_INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: db-instance-connection-name
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false

---
# Service - Exposes Auth service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: swappo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # Internal only, exposed via ingress

---
# Ingress - Optional: For routing multiple services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: swappo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 8000
