# Catalog Service Deployment with Cloud SQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: swappo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      serviceAccountName: default  # Uses workload identity for GCS access
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      # Main application container
      - name: catalog-service
        image: ghcr.io/swapppo/swappo-catalog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        # Database connection (via Cloud SQL Proxy on localhost)
        - name: DATABASE_URL
          value: postgresql://swappo_user:Admin@127.0.0.1:5432/swappo_catalog
        - name: SQL_ECHO
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: SQL_ECHO
        
        # Google Cloud Storage
        - name: USE_GCS
          value: "true"
        - name: GCS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: gcs-bucket-name
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: gcp-project-id
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "$(DB_INSTANCE_CONNECTION_NAME)"
        env:
        - name: DB_INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: db-instance-connection-name
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: swappo
spec:
  selector:
    app: catalog-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP
