# Catalog Service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-uploads-pvc
  namespace: swappo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: swappo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: catalog-service
        image: ghcr.io/swapppo/swappo-catalog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: catalog-database-url
        - name: SQL_ECHO
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: SQL_ECHO
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: catalog-uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: swappo
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # Internal only, exposed via ingress
