# PostgreSQL for Chat Service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-postgres-pvc
  namespace: swappo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
  namespace: swappo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-db
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: POSTGRES_DB
          value: swappo_chat
        - name: POSTGRES_USER
          value: swappo_user
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: chat-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chat-db
  namespace: swappo
spec:
  selector:
    app: chat-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
