# Chat Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: swappo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: chat-service
        image: ghcr.io/swapppo/swappo-chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: chat-database-url
        - name: SQL_ECHO
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: SQL_ECHO
        - name: NOTIFICATION_SERVICE_URL
          value: http://notifications-service:8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: swappo
spec:
  selector:
    app: chat-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # Internal only, exposed via ingress
