# Notifications Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: swappo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      serviceAccountName: default
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      # Main application container
      - name: notifications-service
        image: ghcr.io/swapppo/swappo-notifications:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        # Database connection via Cloud SQL Proxy
        - name: DATABASE_URL
          value: postgresql://notifications_user:Admin@127.0.0.1:5432/swappo_notifications
        - name: SQL_ECHO
          valueFrom:
            configMapKeyRef:
              name: swappo-config
              key: SQL_ECHO
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "$(DB_INSTANCE_CONNECTION_NAME)"
        env:
        - name: DB_INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: swappo-secrets
              key: db-instance-connection-name
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: swappo
spec:
  selector:
    app: notifications-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # Internal only
