# Secrets - Stores sensitive data (base64 encoded)
# IMPORTANT: In production, use proper secret management (e.g., Azure Key Vault, AWS Secrets Manager)
# To encode: echo -n "your-password" | base64
apiVersion: v1
kind: Secret
metadata:
  name: swappo-secrets
  namespace: swappo
type: Opaque
data:
  # Example values - CHANGE THESE IN PRODUCTION
  # "swappo_pass" = c3dhcHBvX3Bhc3M=
  # "swappo_password" = c3dhcHBvX3Bhc3N3b3Jk
  postgres-password: c3dhcHBvX3Bhc3M=
  auth-postgres-password: c3dhcHBvX3Bhc3N3b3Jk
  secret-key: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  refresh-secret-key: eW91ci1yZWZyZXNoLXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
  
  # Full DATABASE_URLs (base64 encoded)
  auth-database-url: cG9zdGdyZXNxbDovL3N3YXBwbzpzd2FwcG9fcGFzc3dvcmRAYXV0aC1kYjo1NDMyL3N3YXBwb19hdXRo
  catalog-database-url: cG9zdGdyZXNxbDovL3N3YXBwb191c2VyOnN3YXBwb19wYXNzQGNhdGFsb2ctZGI6NTQzMi9zd2FwcG9fY2F0YWxvZw==
  matchmaking-database-url: cG9zdGdyZXNxbDovL3N3YXBwb191c2VyOnN3YXBwb19wYXNzQG1hdGNobWFraW5nLWRiOjU0MzIvc3dhcHBvX21hdGNobWFraW5n
  notifications-database-url: cG9zdGdyZXNxbDovL3N3YXBwb191c2VyOnN3YXBwb19wYXNzQG5vdGlmaWNhdGlvbnMtZGI6NTQzMi9zd2FwcG9fbm90aWZpY2F0aW9ucw==
  chat-database-url: cG9zdGdyZXNxbDovL3N3YXBwb191c2VyOnN3YXBwb19wYXNzQGNoYXQtZGI6NTQzMi9zd2FwcG9fY2hhdA==
